# BIND + PROTECTION
bind 0.0.0.0
protected-mode yes

# AUTH
requirepass @ABC12abc

# STORAGE
dir /data
dbfilename dump.rdb

# SNAPSHOTS
save 900 1
save 300 10
save 60 10000

# AOF LOG
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# MEMORY MANAGEMENT
maxmemory 4gb
maxmemory-policy allkeys-lru

# NETWORK
tcp-keepalive 300
timeout 0

# LOGGING
loglevel notice